#!/bin/sh

# create schema
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f /tmp/schema.sql
# create user
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE USER $POSTGRES_USER_TAGSTORE WITH PASSWORD '$POSTGRES_PASSWORD_TAGSTORE';"
# set permissions
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" << EOF
REVOKE CONNECT ON DATABASE "$POSTGRES_DB" FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA tagstore FROM PUBLIC;

GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_USER_TAGSTORE";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA tagstore TO "$POSTGRES_USER_TAGSTORE";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA tagstore TO "$POSTGRES_USER_TAGSTORE";

ALTER SCHEMA tagstore OWNER TO "$POSTGRES_USER_TAGSTORE";
ALTER MATERIALIZED VIEW tagstore.label OWNER TO "$POSTGRES_USER_TAGSTORE";
ALTER MATERIALIZED VIEW tagstore.statistics OWNER TO "$POSTGRES_USER_TAGSTORE";
EOF
# insert confidence table
# Now this values can be ingested by the tool
#psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "\copy tagstore.confidence(id,label,description,level) from 'tmp/confidence.csv' DELIMITER ',' CSV HEADER;"
